# Build on Travis's container-based infrastructure, which starts builds
# much faster:
sudo: false

language: python
python:
  - "2.7"
# command to install dependencies
services:
  - rabbitmq
  - postgresql
  - elasticsearch
addons:
  postgresql: "9.6"
jdk:
  - openjdk8
before_install:
  - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.deb && sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb && sudo service elasticsearch restart
install:
  - pip install -r requirements.txt
  - pip install psycopg2
  - pip install -r requirements_testing.txt
# command to run tests
before_script:
  - psql -c 'create database writeit;' -U postgres
script:
  - wget -q --waitretry=5 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - coverage run --source=nuntium,contactos,mailit,instance manage.py test nuntium contactos mailit instance
  - coverage report -m
after_script:
  - coveralls --verbose
env:
  - DB=postgres ES_VERSION=1.7.5
  - DB=sqlite3 ES_VERSION=1.7.5
